### ISSUE TITLE
Can't Run Any apps, I got a crash report

### ISSUE THREAD

**Issue by iTheGentle** [iqemu64/iqemu64#2]
Hello,
I faced an issue when I try to launch any app, app got crashed, you can see the report bellow:
`Process:               iTorrent [10153]
Path:                  /Users/USER/Library/Developer/CoreSimulator/Devices/60AD37BF-DDB3-401E-A1C9-3CC6B3AAAFCD/data/Containers/Bundle/Application/D232FBE7-2975-4B0E-8E3C-8DEB8DEF4447/iTorrent.app/iTorrent
Identifier:            iTorrent
Version:               1.8.3 (20.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd_sim [10040]
Responsible:           SimulatorTrampoline [398]
User ID:               501

Date/Time:             2022-04-10 14:06:46.636 +0300
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Anonymous UUID:        A138C181-BA23-12F6-BFF6-F03933C21C7E

Time Awake Since Boot: 40000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x9] <unknown>

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=/Users/mojave/Library/Developer/CoreSimulator/Caches/dyld/19F101/com.apple.CoreSimulator.SimRuntime.iOS-13-4.17E8260
DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
DYLD_FALLBACK_FRAMEWORK_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks
DYLD_FALLBACK_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib
DYLD_INSERT_LIBRARIES=/usr/local/lib/libiqemu.dylib
DYLD_LIBRARY_PATH=/usr/local/simulator_bin

Dyld Error Message:
  image not found

Binary Images:
       0x10f4d8000 -        0x10f9cbff3 +ru.nonamedude.iTorrent (1.8.3 - 20.0) <F34A5B1C-6DB7-3F46-A613-EE226AC4B7A7> /Users/USER/Library/Developer/CoreSimulator/Devices/60AD37BF-DDB3-401E-A1C9-3CC6B3AAAFCD/data/Containers/Bundle/Application/D232FBE7-2975-4B0E-8E3C-8DEB8DEF4447/iTorrent.app/iTorrent
       0x10fbb0000 -        0x10fc05d6f +dyld_sim (750.4.2) <C2FDB5FC-0758-32AF-9D4C-DF8F56C98B37> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/dyld_sim
       0x110120000 -        0x110197fff +libc++.1.dylib (0) <ACBEC4E3-04E9-3B82-9365-ECA4CF88B498> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/ARM64/usr/lib/libc++.1.dylib
       0x1101e6000 -        0x1101f9ff3 +org.cocoapods.DeepDiff (2.3.1 - 1) <FC74138A-7AE6-34F7-8ED7-4FDC5B797E6C> /Users/USER/Library/Developer/CoreSimulator/Devices/60AD37BF-DDB3-401E-A1C9-3CC6B3AAAFCD/data/Containers/Bundle/Application/D232FBE7-2975-4B0E-8E3C-8DEB8DEF4447/iTorrent.app/Frameworks/DeepDiff.framework/DeepDiff
       0x110222000 -        0x110235fff +org.cocoapods.FBLPromises (1.2.10 - 1) <0DFACFD1-822F-3EB2-8C1C-7A8C1BFAD42F> /Users/USER/Library/Developer/CoreSimulator/Devices/60AD37BF-DDB3-401E-A1C9-3CC6B3AAAFCD/data/Containers/Bundle/Application/D232FBE7-2975-4B0E-8E3C-8DEB8DEF4447/iTorrent.app/Frameworks/FBLPromises.framework/FBLPromises
       0x11025a000 -        0x110281ff7 +org.cocoapods.GCDWebServer (3.5.4 - 1) <19C3D77F-B4B5-3E21-AD7C-3770E566D012> /Users/USER/Library/Developer/CoreSimulator/Devices/60AD37BF-DDB3-401E-A1C9-3CC6B3AAAFCD/data/Containers/Bundle/Application/D232FBE7-2975-4B0E-8E3C-8DEB8DEF4447/iTorrent.app/Frameworks/GCDWebServer.framework/GCDWebServer
       0x1102c2000 -        0x1102e9ffb +org.cocoapods.GTMSessionFetcher (1.4.0 - 1) <4528B108-37D0-315E-A444-B753C8B334DD> /Users/USER/Library/Developer/CoreSimulator/Devices/60AD37BF-DDB3-401E-A1C9-3CC6B3AAAFCD/data/Containers/Bundle/Application/D232FBE7-2975-4B0E-8E3C-8DEB8DEF4447/iTorrent.app/Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher
       0x11032e000 -        0x110339ffb +org.cocoapods.GoogleToolboxForMac (2.2.2 - 1) <4676A781-4DF5-3715-82AC-3A06382AD8E7> /Users/USER/Library/Developer/CoreSimulator/Devices/60AD37BF-DDB3-401E-A1C9-3CC6B3AAAFCD/data/Containers/Bundle/Application/D232FBE7-2975-4B0E-8E3C-8DEB8DEF4447/iTorrent.app/Frameworks/GoogleToolboxForMac.framework/GoogleToolboxForMac
       0x110352000 -        0x110371ffb +org.cocoapods.GoogleUtilities (6.7.2 - 1) <8BC4CB9C-9FDB-35EF-814F-41272FD40FD3> /Users/USER/Library/Developer/CoreSimulator/Devices/60AD37BF-DDB3-401E-A1C9-3CC6B3AAAFCD/data/Containers/Bundle/Application/D232FBE7-2975-4B0E-8E3C-8DEB8DEF4447/iTorrent.app/Frameworks/GoogleUtilities.framework/GoogleUtilities
       0x1103a6000 -        0x1103bdffb +org.cocoapods.MarqueeLabel (4.0.2 - 1) <BA162A52-BB05-3BCA-ACC4-B752BB68E304> /Users/USER/Library/Developer/CoreSimulator/Devices/60AD37BF-DDB3-401E-A1C9-3CC6B3AAAFCD/data/Containers/Bundle/Application/D232FBE7-2975-4B0E-8E3C-8DEB8DEF4447/iTorrent.app/Frameworks/MarqueeLabel.framework/MarqueeLabel
       0x1103f6000 -        0x110445ffb +org.cocoapods.Protobuf (3.13.0 - 1) <FF9C4A14-6BA5-352D-9C8E-9E503A941178> /Users/USER/Library/Developer/CoreSimulator/Devices/60AD37BF-DDB3-401E-A1C9-3CC6B3AAAFCD/data/Containers/Bundle/Application/D232FBE7-2975-4B0E-8E3C-8DEB8DEF4447/iTorrent.app/Frameworks/Protobuf.framework/Protobuf
       0x1104f6000 -        0x110509ff7 +org.cocoapods.SwiftyXMLParser (5.1.0 - 1) <32C49C95-4222-30DC-8BA1-1990E3A674D7> /Users/USER/Library/Developer/CoreSimulator/Devices/60AD37BF-DDB3-401E-A1C9-3CC6B3AAAFCD/data/Containers/Bundle/Application/D232FBE7-2975-4B0E-8E3C-8DEB8DEF4447/iTorrent.app/Frameworks/SwiftyXMLParser.framework/SwiftyXMLParser
       0x11052e000 -        0x110539fff +org.cocoapods.nanopb (1.30905.0 - 1) <E3E50109-51EF-3BAC-81F6-1296771A9DDB> /Users/USER/Library/Developer/CoreSimulator/Devices/60AD37BF-DDB3-401E-A1C9-3CC6B3AAAFCD/data/Containers/Bundle/Application/D232FBE7-2975-4B0E-8E3C-8DEB8DEF4447/iTorrent.app/Frameworks/nanopb.framework/nanopb
       0x11054a000 -        0x1109ed25f +com.nonamedude.ITorrentFramework (1.0 - 1) <706089C8-79B3-3D34-AE02-50ACF2F126ED> /Users/USER/Library/Developer/CoreSimulator/Devices/60AD37BF-DDB3-401E-A1C9-3CC6B3AAAFCD/data/Containers/Bundle/Application/D232FBE7-2975-4B0E-8E3C-8DEB8DEF4447/iTorrent.app/Frameworks/ITorrentFramework.framework/ITorrentFramework
       0x11199f000 -        0x111a30eff  dyld (750.5) <E4698FBD-806A-3396-B279-E685BA37430B> /usr/lib/dyld
    0x7fff208cf000 -     0x7fff20ae4ff7  com.apple.avfoundation (2.0 - 1841.58) <730AEA53-0D0D-3AAF-AD8F-826F3A6ED7AD> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/AVFoundation.framework/AVFoundation
    0x7fff221cf000 -     0x7fff221cffff  com.apple.AdSupport (1.0 - 1) <19AE8843-97FE-3781-AF67-F7935F15D244> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/AdSupport.framework/AdSupport
    0x7fff22742000 -     0x7fff22861ff9  com.apple.audio.toolbox.AudioToolbox (1.8 - 1.8) <74B2C3C8-4E54-3733-89C9-0EBDB83B3171> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/AudioToolbox.framework/AudioToolbox
    0x7fff22f50000 -     0x7fff232bfffd  com.apple.CFNetwork (1125.2 - 1125.2) <49C550C6-ED3F-32E3-A8D1-43262398315F> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CFNetwork.framework/CFNetwork
    0x7fff23cfe000 -     0x7fff240c1ff5  com.apple.CoreFoundation (6.9 - 1675.129) <187697B0-9ABC-300B-8D2C-C6589A03B841> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
    0x7fff240b5000 -     0x7fff246eeffb  com.apple.CoreGraphics (2.0 - 1355.13) <C18CE67D-D388-365E-83AF-2B74F3BFB539> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics
    0x7fff24d99000 -     0x7fff24e4dff9  com.apple.CoreMedia (1.0 - 2612.58.1.7) <039BC940-D2B8-336D-B321-336A396D62AF> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreMedia.framework/CoreMedia
    0x7fff2515d000 -     0x7fff2523cff9  com.apple.CoreTelephony (113 - 7549.1) <8A236BD7-A6AF-39A1-83BC-8BBFDE37A231> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
    0x7fff253dd000 -     0x7fff2540bff1  com.apple.CoreVideo (1.8 - 344.3) <9A0C8540-FF29-303D-9BCC-08EADD175CF8> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreVideo.framework/CoreVideo
    0x7fff25873000 -     0x7fff25b74ff3  com.apple.Foundation (6.9 - 1675.129) <310ADF4D-4566-351B-A7A7-8AFD9A2D1D4E> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation
    0x7fff26a2f000 -     0x7fff2763dfec  com.apple.JavaScriptCore (8609 - 8609.1.20.0.9) <11D8D51F-18F6-3F56-9A64-8BD1435CE725> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore
    0x7fff27994000 -     0x7fff27d67ff4  com.apple.MediaPlayer (1.0 - 1.0) <ACAEA525-3C31-37B6-9E01-6F3DF14F3D06> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
    0x7fff2819a000 -     0x7fff282f2ff2  com.apple.messageui (1.0.0 - 3608.80.24.1.8) <E5003B48-2C8E-3F58-8704-94C6C01243CD> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/MessageUI.framework/MessageUI
    0x7fff2860a000 -     0x7fff2860aff7  com.apple.MobileCoreServices (1069.17 - 1069.17) <BC40A6C6-26C9-343A-ACF0-F4B59C2EEF6F> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
    0x7fff2b35c000 -     0x7fff2b59dfff  com.apple.QuartzCore (1.11 - 840.18) <C9D448F9-27EA-3F02-9B90-AF0D49E9A3BA> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/QuartzCore.framework/QuartzCore
    0x7fff2b94b000 -     0x7fff2bb21ffe  com.apple.SafariServices (13.1 - 604.1) <638FDB0B-0010-3CE5-B2CA-9FE12D71AB98> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SafariServices.framework/SafariServices
    0x7fff2bf13000 -     0x7fff2c03cfff  com.apple.Security (10.0 - 59306.102.1) <F015ED73-1D51-3488-8D0F-5206B2B5B365> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Security.framework/Security
    0x7fff2c30c000 -     0x7fff2c34cffd  com.apple.StoreKit (1.0 - 1) <C240D756-9FC1-317B-813D-8358795E9A6A> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/StoreKit.framework/StoreKit
    0x7fff2ca6d000 -     0x7fff2cacfff7  com.apple.SystemConfiguration (1.19 - 1.19) <AC689BCF-9500-3B1F-B185-4720F8EB34AF> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
    0x7fff2cad2000 -     0x7fff2cad2fff  com.apple.UIKit (1.0 - 61000) <2FDEED32-19DB-38F0-A11E-6452EF25232C> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UIKit.framework/UIKit
    0x7fff2cad3000 -     0x7fff2cb07ff4  com.apple.UserNotifications (1.0 - ???) <EB63DA64-8E8C-39F7-9EEC-18B41F76E46E> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/UserNotifications.framework/UserNotifications
    0x7fff2d238000 -     0x7fff2d92bff2  com.apple.WebKit (8609 - 8609.1.20.0.9) <FD3AF314-BAD7-3D98-ABDC-45B50A6F1810> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/WebKit.framework/WebKit
    0x7fff4f5e6000 -     0x7fff4f5e7ff7 +libSystem.B.dylib (1281.100.1) <B7EB8E8F-D166-307B-BD24-F3493CE09022> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.B.dylib
    0x7fff50ad2000 -     0x7fff50afeff6 +libobjc.A.dylib (787.1) <BBE7987D-BDB4-35B2-B8C5-0E85BD96D8C3> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libobjc.A.dylib
    0x7fff50ba4000 -     0x7fff50d40ff7 +libsqlite3.dylib (308.4) <9515C7B6-75A8-3FA1-B4A2-F7F224B5554E> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libsqlite3.dylib
    0x7fff50dcf000 -     0x7fff50eb1ffb +libxml2.2.dylib (33.3) <4F813F8A-FE58-3101-8D47-F0E2AC45883A> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libxml2.2.dylib
    0x7fff50ede000 -     0x7fff50ef0ff7 +libz.1.dylib (76) <A070B5EB-EF97-3C59-A839-50E3EA16AC33> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libz.1.dylib

`
thank you in advance.

**Comment by frefire** [comment]
Did you load the kernel extension correctly?

**Comment by goodtomeetyou** [comment]
> Did you load the kernel extension correctly?

Did you ran the project successfully? I want to port it for macOS Tahoe but dyld and xnu patching became more harder on latest versions
