### ISSUE TITLE
Can't Install Kext

### ISSUE THREAD

**Issue by sdfwss** [iqemu64/iqemu64#3]
安装kext文件时，出现以下错误，模拟器中的App仍会闪退
`Notice: /private/tmp/iemukern.kext has debug properties set.
Kext with invalid signature (-67062) allowed: <OSKext 0x7f9123d06580 [0x7fff8a5b2cc0]> { URL = "file:///private/tmp/iemukern.kext/", ID = "com.cod.iemukern" }
Code Signing Failure: not code signed`

**Comment by frefire** [comment]
有没有关闭mac OS的SIP

**Comment by sdfwss** [comment]
> 有没有关闭mac OS的SIP

关闭了
`csrutil status`显示`System Integrity Protection status: disabled.`

**Comment by sdfwss** [comment]
编译输出：
https://pastebin.ubuntu.com/p/zqsXCkgKWG/

**Comment by frefire** [comment]
https://developer.apple.com/forums/thread/109455
